version: "3.8"
services:
  elastic:
    image: ${DC_ELASTIC_IMAGE}
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    volumes:
      - es_data:/usr/share/elasticsearch/data:rw
    ports:
      - 127.0.0.1:${DC_ELASTIC_PORT}:9200
    networks:
      default:
        aliases:
          - ${DC_ELASTIC_HOST}
  minio:
    image: ${DC_MINIO_IMAGE}
    environment:
      TZ: ${DC_TZ}
      MINIO_ACCESS_KEY: ${DC_MINIO_ACCESSKEY}
      MINIO_SECRET_KEY: ${DC_MINIO_SECRETKEY}
      MINIO_HTTP_TRACE: /dev/stdout
    volumes:
      - minio_cfg:/root/.minio:rw
      - minio_data:/data:rw
    command: ["server", "/data"]
    ports:
      - 127.0.0.1:${DC_MINIO_PORT}:9000
    networks:
      default:
        aliases:
          - ${DC_MINIO_HOST}
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${DC_APP_ARCH}
      args:
        BASE_IMG: ${DC_APP_BASE_IMAGE}
    depends_on:
      - minio
      - elastic
    ports:
      - 127.0.0.1:${DC_APP_PORT}:${CB_APP_PORT}
    networks:
      default:
        aliases:
          - ${DC_APP_HOST}
  nginx:
    image: ${DC_PROXY_IMAGE}
    environment:
      TZ: ${DC_TZ}
      HTTP_PORT: 80
      APP_HOST: ${DC_APP_HOST}
      APP_PORT: ${DC_APP_PORT}
    volumes:
      - ./build/proxy.conf:/etc/nginx/templates/default.conf.template:ro
    ports:
      - 127.0.0.1:${DC_NGINX_PORT}:80
    depends_on:
      - app
volumes:
  es_data:
    driver: local
  minio_cfg:
    driver: local
  minio_data:
    driver: local
